name: RSS Summary to Log

on:
  workflow_dispatch:

jobs:
  rss_to_log:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch RSS Feeds
        id: fetch
        run: |
          FEEDS=(
            "https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml"
            "http://rss.itmedia.co.jp/rss/2.0/news_foreign.xml"
            "https://rss.itmedia.co.jp/rss/2.0/news_security.xml"
            "https://rss.itmedia.co.jp/rss/2.0/aiplus.xml"
            "https://aws.amazon.com/jp/about-aws/whats-new/recent/feed/"
          )
          echo "Fetching RSS feeds..."
          rm -f all_feeds.xml
          for url in "${FEEDS[@]}"; do
            curl -fsL "$url" >> all_feeds.xml || echo "Failed to fetch $url"
          done
          
          # Base64 エンコードして出力
          ENCODED=$(base64 -w 0 all_feeds.xml)
          echo "raw_xml_b64=${ENCODED}" >> "$GITHUB_OUTPUT"

      - name: Summarize with Gemini
        id: gemini
        uses: google-github-actions/run-gemini-cli@v0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          model: "gemini-2.5-pro"
          prompt: |
            以下のBase64エンコードされた複数RSSフィードの生データをデコードし、
            発行日時が過去24時間以内の新しい記事のみを抽出してください。
            その後、抽出した全記事の内容を統合し、最も重要なトピックを洗い出し、
            それぞれを箇条書きで簡潔に要約してください。

            重要なトピック：
            1. ITエンジニアに関わる内容
            2. AI、クラウド、セキュリティに関連する内容

            要約の最後には、参考にした記事のタイトルとリンクをリスト形式で必ず記載してください。
            ---
            BASE64データ: ${{ steps.fetch.outputs.raw_xml_b64 }}
            ---
