name: RSS Summary to Log

on:
  workflow_dispatch:

jobs:
  rss_to_log:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch RSS Feeds
        id: fetch
        run: |
          FEEDS=(
            "https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml"
            "http://rss.itmedia.co.jp/rss/2.0/news_foreign.xml"
            "https://rss.itmedia.co.jp/rss/2.0/news_security.xml"
            "https://rss.itmedia.co.jp/rss/2.0/aiplus.xml"
            "https://aws.amazon.com/jp/about-aws/whats-new/recent/feed/"
            "https://research.google/blog/rss/"
          )
          echo "Fetching RSS feeds..."
          rm -f all_feeds.xml
          for url in "${FEEDS[@]}"; do
            curl -fsL "$url" >> all_feeds.xml || echo "Failed to fetch $url"
          done

      - name: Summarize with Gemini
        id: gemini
        uses: google-github-actions/run-gemini-cli@v0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          model: "gemini-2.5-pro"
          prompt: |
            以下のRSSフィードの内容（XMLやその他）から、
            発行日時が前日の記事のみ抽出し、
            重要なトピックを要約し、英語は日本語に翻訳してください。（日付が合ってるかも知りたいので、日付も書いて下さい。）

            重要なトピック：
            AI、クラウド、セキュリティ関連

            要約の最後に記事タイトルとリンクを列挙してください。
            ---
            ${{ steps.readfile.outputs.content }}
            ---

      - name: Read XML into output
        id: readfile
        run: |
          CONTENT=$(cat all_feeds.xml)
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
