name: RSS Summary to Log

on:
  workflow_dispatch:

jobs:
  rss_to_log:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch RSS Feeds
        id: fetch
        run: |
          FEEDS=(
            "https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml"
            "http://rss.itmedia.co.jp/rss/2.0/news_foreign.xml"
            "https://rss.itmedia.co.jp/rss/2.0/news_security.xml"
            "https://rss.itmedia.co.jp/rss/2.0/aiplus.xml"
          )
          echo "Fetching RSS feeds..."
          for url in "${FEEDS[@]}"; do
            curl -fsL "$url" >> all_feeds.xml || echo "Failed to fetch $url"
          done
          {
            echo "raw_xml<<EOF"
            cat all_feeds.xml
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Summarize with Gemini
        id: gemini
        uses: google-github-actions/run-gemini-cli@v0
        # with: ではなく env: でAPIキーを渡すのが正しい仕様
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        with:
          model: "gemini-2.5-pro"
          prompt: |
            あなたは優秀なアシスタントです。
            以下の複数のRSSフィードの生データ（XML形式）から、発行日時が過去24時間以内の新しい記事のみを抽出してください。
            その後、抽出した全記事の内容を統合し、最も重要なトピックを3つに絞って、それぞれを箇条書きで簡潔に要約してください。
            要約の最後には、参考にした記事のタイトルとリンクをリスト形式で必ず記載してください。

            ---
            ${{ steps.fetch.outputs.raw_xml }}
            ---
      
      - name: Print Summary to Log
        run: |
          echo "--- Gemini Summary Result ---"
          echo "${{ steps.gemini.outputs.result }}"
          echo "-----------------------------"
